import type { AppConfig } from '../types.ts';

export const sampleWeatherConfig: AppConfig = {
  meta: {
    title: 'Local on the 8s',
    pageCycleDurationMs: 10000,
    transitionType: 'fade',
    transitionDurationMs: 800,
  },
  header: {
    title: 'Your Local Forecast',
    showClock: true,
    clockFormat: '12h',
    logoText: 'THE\nWEATHER\nCHANNEL',
  },
  pages: [
    {
      type: 'data-grid',
      title: 'Current Conditions',
      rows: [
        { label: 'Temperature', value: '72\u00b0F' },
        { label: 'Feels Like', value: '74\u00b0F' },
        { label: 'Humidity', value: '65%' },
        { label: 'Wind', value: 'SW 8 mph' },
        { label: 'Barometer', value: '30.12 in' },
        { label: 'Dewpoint', value: '59\u00b0F' },
        { label: 'Visibility', value: '10 mi' },
        { label: 'UV Index', value: '6 High' },
      ],
    },
    {
      type: 'forecast',
      title: '5-Day Forecast',
      cards: [
        { label: 'Mon', icon: '\u2600\ufe0f', primary: '78\u00b0', secondary: 'Lo 62\u00b0' },
        { label: 'Tue', icon: '\u26c5', primary: '74\u00b0', secondary: 'Lo 58\u00b0' },
        { label: 'Wed', icon: '\ud83c\udf27\ufe0f', primary: '68\u00b0', secondary: 'Lo 55\u00b0' },
        { label: 'Thu', icon: '\u26c8\ufe0f', primary: '65\u00b0', secondary: 'Lo 52\u00b0' },
        { label: 'Fri', icon: '\u2600\ufe0f', primary: '76\u00b0', secondary: 'Lo 60\u00b0' },
      ],
    },
    {
      type: 'data-grid',
      title: 'Market Update',
      rows: [
        { label: 'S&P 500', value: '4,587.64  +0.42%' },
        { label: 'DJIA', value: '35,842.18  +0.38%' },
        { label: 'NASDAQ', value: '14,261.50  +0.57%' },
        { label: 'Bitcoin', value: '$43,218  +2.3%' },
        { label: 'Gold', value: '$2,041.30  +8.50' },
        { label: 'Crude Oil', value: '$78.42  +1.15' },
        { label: '10-Yr Treasury', value: '4.32%  -0.02' },
        { label: 'VIX', value: '13.42' },
      ],
    },
    {
      type: 'bar-chart',
      title: 'Regional High Temps',
      unit: '\u00b0',
      bars: [
        { label: 'DT', value: 78, color: '#ff6644' },
        { label: 'APT', value: 71, color: '#ff8844' },
        { label: 'MID', value: 82, color: '#ff4422' },
        { label: 'LKF', value: 69, color: '#44bbff' },
        { label: 'N.SUB', value: 74, color: '#ff8844' },
        { label: 'S.SUB', value: 85, color: '#ff3311' },
        { label: 'HILL', value: 67, color: '#44bbff' },
        { label: 'VAL', value: 88, color: '#ff2200' },
      ],
    },
    {
      type: 'table',
      title: 'Almanac',
      columns: ['Metric', 'Today', 'Normal', 'Record'],
      rows: [
        ['High Temp', '78\u00b0F', '75\u00b0F', '98\u00b0F (1988)'],
        ['Low Temp', '62\u00b0F', '58\u00b0F', '34\u00b0F (1972)'],
        ['Precip', '0.00 in', '0.12 in', '2.45 in (1995)'],
        ['Sunrise', '6:42 AM', '', ''],
        ['Sunset', '8:18 PM', '', ''],
        ['Moon Phase', 'Waxing Gibbous', '', ''],
      ],
    },
    {
      type: 'forecast',
      title: 'Daily Horoscope',
      cards: [
        { label: 'Aries', icon: '\u2648', primary: '\u2605\u2605\u2605\u2605', secondary: 'Bold moves pay off' },
        { label: 'Taurus', icon: '\u2649', primary: '\u2605\u2605\u2605', secondary: 'Financial focus' },
        { label: 'Gemini', icon: '\u264a', primary: '\u2605\u2605\u2605\u2605', secondary: 'Communication key' },
        { label: 'Cancer', icon: '\u264b', primary: '\u2605\u2605\u2605\u2605\u2605', secondary: 'Home & family day' },
        { label: 'Leo', icon: '\u264c', primary: '\u2605\u2605\u2605', secondary: 'Creative energy' },
      ],
    },
    {
      type: 'data-grid',
      title: 'Regional Observations',
      rows: [
        { label: 'Downtown', value: '73\u00b0F  Sunny' },
        { label: 'Airport', value: '71\u00b0F  Clear' },
        { label: 'Midtown', value: '74\u00b0F  Sunny' },
        { label: 'Lakefront', value: '69\u00b0F  Breezy' },
        { label: 'Suburbs North', value: '72\u00b0F  Clear' },
        { label: 'Suburbs South', value: '75\u00b0F  Sunny' },
        { label: 'Hills', value: '67\u00b0F  Partly Cloudy' },
        { label: 'Valley', value: '76\u00b0F  Clear' },
      ],
    },
    {
      type: 'table',
      title: 'Top Movers',
      columns: ['Symbol', 'Price', 'Change', 'Volume'],
      rows: [
        ['NVDA', '$487.21', '+4.82%', '52.3M'],
        ['AAPL', '$185.64', '+1.23%', '48.1M'],
        ['TSLA', '$242.18', '-2.15%', '112.7M'],
        ['MSFT', '$378.45', '+0.87%', '22.4M'],
        ['AMZN', '$153.28', '+1.45%', '35.6M'],
        ['META', '$352.67', '+2.34%', '18.9M'],
        ['GOOGL', '$141.52', '+0.65%', '24.3M'],
      ],
    },
    {
      type: 'freeform',
      title: 'Weather Alert',
      html: '<h2>Heat Advisory</h2><p>A Heat Advisory is in effect from <strong>12 PM Tuesday</strong> through <strong>8 PM Wednesday</strong>.</p><p>Temperatures may reach <strong>95\u00b0F to 100\u00b0F</strong> with heat index values up to <strong>108\u00b0F</strong>.</p><p>Drink plenty of fluids, stay in air-conditioned rooms, and check on elderly neighbors.</p>',
    },
    {
      type: 'forecast',
      title: 'Horoscope (Continued)',
      cards: [
        { label: 'Virgo', icon: '\u264d', primary: '\u2605\u2605\u2605\u2605', secondary: 'Details matter' },
        { label: 'Libra', icon: '\u264e', primary: '\u2605\u2605\u2605', secondary: 'Seek balance' },
        { label: 'Scorpio', icon: '\u264f', primary: '\u2605\u2605\u2605', secondary: 'Transformation' },
        { label: 'Sagittarius', icon: '\u2650', primary: '\u2605\u2605\u2605\u2605\u2605', secondary: 'Adventure awaits' },
        { label: 'Capricorn', icon: '\u2651', primary: '\u2605\u2605\u2605', secondary: 'Patience rewarded' },
      ],
    },
    {
      type: 'data-grid',
      title: 'Tides & Marine Forecast',
      rows: [
        { label: 'High Tide', value: '4:32 AM  5.2 ft' },
        { label: 'Low Tide', value: '10:48 AM  0.8 ft' },
        { label: 'Water Temp', value: '68\u00b0F' },
        { label: 'Wave Height', value: '2-3 ft' },
        { label: 'Surf Advisory', value: 'None' },
        { label: 'Rip Current Risk', value: 'Low' },
        { label: 'Wind Offshore', value: 'E 12 kts' },
        { label: 'Visibility', value: '8 nm' },
      ],
    },
  ],
  ticker: {
    enabled: true,
    items: [
      'Heat Advisory in effect Tue-Wed',
      'High near 78\u00b0F today',
      'S&P 500 +0.42% | DJIA +0.38% | NASDAQ +0.57%',
      'Rain chances increase Wednesday 60%',
      'Mercury direct \u2014 communication clears up',
      'NVDA leads tech rally +4.82%',
      'Weekend outlook: Sunny and warm',
      'Full Moon in Leo this Friday',
      'Air Quality Index: Good (42)',
      'Bitcoin $43,218 +2.3%',
      'Pollen Count: Moderate',
      'Venus enters Pisces \u2014 romance heightened',
      'UV Index: 6 (High) \u2014 Wear sunscreen',
    ],
    speedPixelsPerSecond: 80,
    separator: '\u2022',
  },
  audio: {
    enabled: true,
    tracks: [
      { name: 'Smooth Jazz 1', url: '/audio/happinessinmusic-the-jazz-482573.mp3' },
      { name: 'Smooth Jazz 2', url: '' },
      { name: 'Smooth Jazz 3', url: '' },
    ],
    volume: 0.6,
    crossfadeDurationS: 3,
    shuffle: false,
    autoplay: true,
  },
};
